// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmopracxcszsbylonbno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indtb3ByYWN4Y3N6c2J5bG9uYm5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NTgyOTUsImV4cCI6MjA3MzIzNDI5NX0.x2RThimSmoFtGTxSvipHN8ifapeO2kK3Vh0hZxKNZpE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});